#+title: Interesting takes on web development

I'm always impressed by how different programming language features could affect your style of writing web applications. There are a lot of languages you can write code for the web application: Java, Ruby, Elixir, Scala, Haskell and though they provide some interesting insights into application development, I'm more interested in less mainstream languages.

In this article we'll take a look at how to build a small database-backed web application in ATS, Idris and Ur. Each of them have very interesting language features I would love to show you and compare.

Our application would be a rather straightforward one, it's just a todo list with authentication and authorization.

Some job stories

1. When opening site for the first time, I want to see login page so I can access my dashboard.
2. When item added to the dashboard, I want to see a feedback so I can avoid resubmitting the data.

Let's quickly talk about my language list before jumping to code?

- ATS :: my working horse, absolutely fantastic language if you have a lot of free time
- Idris :: practical programming language with dependent types
- Ur :: language specifically design for a secure web-development and contains few interesting type system features
