#+title: TLA+ intro

Welcome to a small TLA+ tutorial. In this tutorial I will introduce TLA+, TLA+ toolbox.

We will talk about why we need TLA+, what is the philosophy of this tool, what class of problems is suitable for TLA+ modeling and other things.

I want to be as practical and hands on as possible. So I will introduce mathematical foundations of TLA+ as we go, and touch practical things. There are multiple ways to run TLA+, I will use TLA+ toolbox in my series, but you are free to try VS Code extension, or any other editor of your choice.

It might be easier to follow this series if you stick to TLA+ toolbox though.

Visit this website to get an instructions on how to install TLA+ and when you are done, come back to this article.

[[https://lamport.azurewebsites.net/tla/toolbox.html][TLA+ toolbox page]]

After the installation you should be able to login to TLA+ studio. Please watch a brief intro on how to use it here [link to youtube].

In this article I want to give you some answers to the WHY? questions. Why we need TLA+, what problems are extremely suitable for TLA+ computational model.

TLA+ is a tool to build and verify models for your software systems. It is suitable not only for software systems, but basically for any type of systems.

And in the following articles I will talk about modeling network level algorithms for network packet transfer, modeling analogues clock, and modeling life and death.

Why is it possible with TLA+? Because it is not just a programming language, TLA+ is a set of tools that includes a notation (aka. express specification in a text form). Checker and IDE. My suggestion for learning TLA+ is the same as for learning a new foreign language (or a new paradigm in programming languages) very different from yours.

Try to be open-minded, because writing specification is closer to writing mathematical formulas, and not writing the computer programs, so you will have to work through a somewhat steep learning curve, but I will take your hand and guide you through the whole process.

To be precisie TLA+ still has some resemblense to functional programming language, but don't let this resemblense lead you in the wrong way and make you think that you are writing a program. You don't. You describe the behaviour of the system in time.

Now, we will test your TLA+ setup and write some simple specification just to see if we are ready to move forward.

Let's create a new specification and write this

#+begin_src tla
module Clock

vars hour

Next == hour' = 3

Spec == [][Next]_hour
#+end_src

In this tutorial I will try to never leave any untold and implicit elements, but as in any educational material I will have to introduce them step by step, and sometimes it is gonna be ugly. I will have to lie to you and simplify the idea behind TLA+ that much, that it almost sounds incorrect to the person who understand theory behind it. I will remember all the places where I did this and before you finish the last chapter you will have full and correct model in your head. I promise.
